# Generated by Django 3.2 on 2021-06-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20210614_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user',
            new_name='created_by',
        ),
    ]
